language: rust
rust:
- nightly
sudo: required
os:
- linux
rust:
- nightly
before_script:
- rustup component add clippy
- rustup component add rustfmt
script:
- cargo clippy --all-features --all-targets -- -D warnings
- cargo fmt -- --check
- cargo build --verbose --features "pulseaudio_backend"
- cargo build --release
- zip -j spotifyd-`date --iso-8601`-amd64.zip target/release/spotifyd
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y libasound2-dev portaudio19-dev build-essential libpulse-dev libdbus-1-dev
deploy:
  provider: releases
  api_key:
    secure: TwIv65LDHIBOgOsafV/wio+EwoG0pg5sFZZvEgNIV5J++zJoxaI35DH1/frKB6S4J2HhEKDojc7Np4tEgNUCOj+qZ51ma85SYr3SzVOg2n/TUI7lg/Gb13n6qd1AfTA2SsTryuGIvS7p4BaYSRtGXUuOghZg+7qdgl+zKeXiLnY=
  file_glob: true
  file: "spotifyd*zip"
  skip_cleanup: true
  on:
    branch: master
    tags: true
