[package]
name = "spotifyd"
version = "0.2.1"
authors = ["Simon Persson <simon@flaskpost.org>"]

[dependencies]
simplelog = "0.4"
xdg = "2.1"
ctrlc = { version = "3.1", features = ["termination"] }
rust-ini = "0.10"
getopts = "0.2"
log = "0.3"
syslog = "3.3"
daemonize = "0.2"
futures = "0.1"
tokio-core = "0.1"
tokio-signal = "0.1"
tokio-io = "0.1"
hostname = "0.1"
rust-crypto = "0.2.36"
dbus = { version = "0.6", optional = true }
dbus-tokio = { version = "0.2", optional = true }
rspotify = "0.1.2"
chrono = "0.4"
alsa = { version = "0.2", optional = true }

[replace]
"rust-crypto:0.2.36" = { git = "https://github.com/awmath/rust-crypto.git", branch = "avx2" }

[dependencies.librespot]
git = "https://github.com/librespot-org/librespot.git"
default-features = false
features = ["with-tremor"]

[features]
alsa_backend = ["librespot/alsa-backend", "alsa"]
pulseaudio_backend = ["librespot/pulseaudio-backend"]
portaudio_backend = ["librespot/portaudio-backend"]
dbus_mpris = ["dbus", "dbus-tokio"]
default = ["alsa_backend"]
