[package]
name = "spotifyd"
version = "0.2.7"
authors = ["Simon Persson <simon@flaskpost.org>"]
edition = "2018"

[dependencies]
simplelog = "0.4"
xdg = "2.2"
rust-ini = "0.13"
getopts = "0.2"
log = "0.4.6"
syslog = "4.0.1"
daemonize = "0.3"
futures = "0.1"
tokio-core = "0.1"
tokio-signal = "0.1"
tokio-io = "0.1"
hostname = "0.1"
rust-crypto = "0.2.36"
dbus = { version = "0.6", optional = true }
dbus-tokio = { version = "0.2", optional = true }
rspotify = "0.2.5"
chrono = "0.4"
alsa = { version = "0.2", optional = true }
keyring = { version = "0.6.1", optional = true }

[dependencies.librespot]
git = "https://github.com/librespot-org/librespot.git"
default-features = false
features = ["with-tremor"]

[replace]
"rust-crypto:0.2.36" = { git = "https://github.com/awmath/rust-crypto.git", branch = "avx2" }

[features]
alsa_backend = ["librespot/alsa-backend", "alsa"]
pulseaudio_backend = ["librespot/pulseaudio-backend"]
portaudio_backend = ["librespot/portaudio-backend"]
dbus_mpris = ["dbus", "dbus-tokio"]
dbus_keyring = ["keyring"]
default = ["alsa_backend"]
