[package]
name = "spotifyd"
version = "0.1.0"
authors = ["Simon Persson <simon@flaskpost.org>"]

[dependencies]
simplelog = "^0.4.2"
xdg = "^2.0"
ctrlc = { version = "2.0", features = ["termination"] }
rust-ini = {git="https://github.com/zonyitoo/rust-ini.git"}
getopts = "^0.2.14"
log = "^0.3.6"
syslog = "^3.1.0"
daemonize = "^0.2.3"
rpassword = "^0.3"
futures = "*"
tokio-core = "0.1.6"
tokio-signal = "0.1.2"
tokio-io = "0.1.1"
hostname = "0.1.3"

[dependencies.librespot]
git = "https://github.com/plietar/librespot.git"
default-features = false
features = ["with-tremor"]

[features]
alsa = ["librespot/alsa-backend"]
pulseaudio = ["librespot/pulseaudio-backend"]
default = ["alsa"]
